backend:
  # local test
  # name: test-repo
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Events"
        name: "events page"
        file: "src/content/events.md"
        fields:
          - label: "Events"
            name: "events"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Banner", name: "banner", widget: "image" }
              - { label: "Slug", name: "slug", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - label: "Sponsors"
                name: "sponsors"
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Logo", name: "logo", widget: "image" }
                  - { label: "Link", name: "link", widget: "string" }
              - label: "Gallery"
                name: "gallery"
                widget: list
                fields:
                  - { label: "Image", name: "src", widget: "image" }
                  - { label: "Width", name: "width", widget: "number" }
                  - { label: "Height", name: "height", widget: "number" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - label: "Testimonials"
                name: "testimonials"
                widget: list
                fields:
                  - { label: "Author", name: "author", widget: "string" }
                  - { label: "Content", name: "content", widget: "text" }
